version: '3.7'
services:
  mysql:
    image: mysql:8.0
    container_name: sf5_mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sf5_phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql

  nginx:
    image: nginx:1.19.0-alpine
    container_name: sf5_nginx
    restart: on-failure
    volumes:
      - './src/public:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '81:80'
    depends_on:
      - php

  php:
    container_name: sf5_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './src/:/usr/src/app'
      - './docker/php/conf/php.ini:/usr/local/etc/php/php.ini'
    restart: on-failure
    env_file:
      - .env
    user: ${LOCAL_USER}

#  node:
#    container_name: sf5_node
#    build:
#      context: .
#      dockerfile: docker/node/Dockerfile
#    volumes:
#      - './src/:/usr/src/app'
#    command: bash -c "yarn && yarn dev"

